targets:
  $default:
    builders:
      mobx_codegen|mobx_generator:
        generate_for:
          - "lib/**_store.dart"
          - "lib/**_controller.dart"
      freezed:
        generate_for:
          - "lib/**_model.dart"
          - "lib/app/core/models/**_status.dart"
        options:
          make_collections_unmodifiable: false
